version: "3.9"
services:
  # Service tidy updates the go.mod to the latest
  tidy:
    build:
      context: ..
      dockerfile: ./.github/Dockerfile
      args:
        VARIANT: alpine
    volumes:
      - ..:/workspaces
    entrypoint: [ "./.github/go-mod-tidy.sh" ]
  # Service min runs the tests on minimum supported Go version
  min:
    build:
      context: ..
      dockerfile: ./.github/Dockerfile
      args:
        VARIANT: 1.17-alpine
    volumes:
      - ..:/workspaces
  # Service latest runs the tests on latest Go docker image
  latest:
    build:
      context: ..
      dockerfile: ./.github/Dockerfile
      args:
        VARIANT: alpine
    volumes:
      - ..:/workspaces
