name: Go Versions

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  schedule:
    # Runs at 16:05 UTC on day-of-month 1 (Every day-of-month 1 at AM 01:05 JST, my time)
    # See: https://crontab.guru/
    - cron: '5 16 1 * *'

env:
  PATH_CACHE: /tmp/docker-img-arch

jobs:
  go:
    name: Run tests on Go via container
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Run tests on minimum supported Go version
        run: docker compose --file ./.github/docker-compose.yml run min

      - name: Run tests on latest Go
        run: docker compose --file ./.github/docker-compose.yml run latest
