# This workflow runs the unit test on vaious platforms such as:
#   Linux, macOS and Windows
name: Platforms

on:
  workflow_dispatch:
  pull_request:
  release:

jobs:
  unit_test:
    name: Platform

    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-go@v6
        with:
          go-version: '1'
          cache: 'go'

      - name: Run unit test
        run: |
          go mod download
          go test -race -v ./...
