# This workflow runs the unit test on vaious platforms such as:
#   Linux, macOS and Windows
name: Platforms

on:
  workflow_dispatch:
  pull_request:
  release:

jobs:
  unit_test:
    name: Platform

    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17'

      - name: Use Cache
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Download Modules
        if: steps.cache.outputs.cache-hit != 'true'
        run: go mod download

      - name: Run unit test
        run: |
          go mod download
          go test -race -v ./...
